# Generated by Django 3.1.2 on 2021-02-19 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='date_used',
            field=models.DateTimeField(null=True, verbose_name='Date Used'),
        ),
    ]
