# Generated by Django 3.1.2 on 2021-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20210219_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='status',
            field=models.CharField(default='active', max_length=15, verbose_name='Status'),
        ),
    ]
