# Generated by Django 3.1.2 on 2021-02-06 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Reservation Id')),
                ('reference', models.CharField(max_length=12, verbose_name='Reference')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('status', models.CharField(max_length=15, verbose_name='Reservation Status')),
                ('credit_balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Credit Balance')),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount Spent')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_created_by', to='staff.staffmodel', verbose_name='Created By')),
            ],
            options={
                'db_table': 'hms_reservation',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
