# Generated by Django 3.1.2 on 2021-02-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='gender',
            field=models.CharField(default='male', max_length=15, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
