# Generated by Django 3.1.2 on 2021-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservationmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Spent'),
        ),
    ]
