# Generated by Django 3.1.2 on 2021-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20210206_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='reference',
            field=models.CharField(max_length=12, unique=True, verbose_name='Reference'),
        ),
    ]
