# Generated by Django 3.1.2 on 2021-02-11 23:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('reservation', '0004_auto_20210206_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Reservation Id')),
                ('channel', models.CharField(max_length=25, verbose_name='Payment Channel')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount Paid')),
                ('amount_unpaid', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount Unpaid')),
                ('status', models.CharField(max_length=15, verbose_name='Payment Status')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staffmodel', verbose_name='Registered By')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.reservationmodel', verbose_name='Reservation')),
            ],
            options={
                'db_table': 'hms_payment',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
