# Generated by Django 3.1.2 on 2021-02-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_paymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='narration',
            field=models.CharField(default='', max_length=255, verbose_name='Narration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='amount_unpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Unpaid'),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='corporate_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Corporate'),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='reservation_type',
            field=models.CharField(default='individual', max_length=50, verbose_name='Reservation Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Last Name'),
        ),
    ]
