# Generated by Django 3.1.2 on 2021-02-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20210216_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='gender',
            field=models.CharField(max_length=15, null=True, verbose_name='Gender'),
        ),
    ]
