# Generated by Django 3.1.2 on 2021-02-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20210216_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Order Id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'db_table': 'hms_order',
            },
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='amount_unpaid',
        ),
    ]
