# Generated by Django 3.1.2 on 2021-02-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('reservation', '0009_ordermodel_order_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='override_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_override_by', to='staff.staffmodel', verbose_name='Override By'),
        ),
    ]
