# Generated by Django 3.1.2 on 2021-03-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_reservationmodel_override_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='client',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Client'),
        ),
    ]
