# Generated by Django 3.1.2 on 2021-03-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_ordermodel_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='client',
            field=models.CharField(max_length=25, null=True, verbose_name='Client'),
        ),
    ]
