# Generated by Django 3.1.2 on 2021-02-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('bar', '0002_drinkordermodel_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkordermodel',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staffmodel', verbose_name='Registered By'),
        ),
    ]
