# Generated by Django 3.1.2 on 2021-02-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20210216_0814'),
        ('bar', '0003_auto_20210211_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkordermodel',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.paymentmodel', verbose_name='Payment Id'),
        ),
    ]
