# Generated by Django 3.1.2 on 2021-02-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20210218_1335'),
        ('bar', '0004_drinkordermodel_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkordermodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.ordermodel', verbose_name='Order Id'),
        ),
    ]
