# Generated by Django 3.1.2 on 2021-02-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommodel',
            old_name='Description',
            new_name='description',
        ),
    ]
