# Generated by Django 3.1.2 on 2021-02-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20210209_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecordmodel',
            name='status',
            field=models.CharField(default='active', max_length=15, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
