# Generated by Django 3.1.2 on 2021-02-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_bookingrecordmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrecordmodel',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
