# Generated by Django 3.1.2 on 2021-02-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20210209_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrecordmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
    ]
