# Generated by Django 3.1.2 on 2021-02-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('room', '0005_auto_20210209_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecordmodel',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staffmodel', verbose_name='Booked By'),
        ),
    ]
