# Generated by Django 3.1.2 on 2021-02-16 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20210216_1212'),
        ('room', '0006_bookingrecordmodel_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecordmodel',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.paymentmodel', verbose_name='Payment Id'),
        ),
    ]
