# Generated by Django 3.1.2 on 2021-03-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_roommodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='category',
        ),
    ]
