# Generated by Django 3.1.2 on 2021-02-20 06:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Option Id')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Option Name')),
                ('value', models.TextField(verbose_name='Option Value')),
            ],
            options={
                'db_table': 'hms_options',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
