# Generated by Django 3.1.2 on 2021-01-26 09:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'hms_auth',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthTokenModel',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expires', models.DateTimeField(default=datetime.datetime(2021, 1, 26, 9, 50, 13, 445659, tzinfo=utc), verbose_name='Expires')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bip_auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'hms_auth_token',
            },
        ),
    ]
