# Generated by Django 3.1.2 on 2021-02-06 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 11, 34, 21, 780824, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
