# Generated by Django 3.1.2 on 2021-02-06 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0003_auto_20210206_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 14, 48, 56, 245405, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
