# Generated by Django 3.1.2 on 2021-02-06 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0005_auto_20210206_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 15, 37, 8, 838783, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
