# Generated by Django 3.1.2 on 2021-02-08 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0006_auto_20210206_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 13, 47, 11, 384570, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
