# Generated by Django 3.1.2 on 2021-02-09 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0007_auto_20210208_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 9, 41, 51, 319093, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
