# Generated by Django 3.1.2 on 2021-02-09 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0008_auto_20210209_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 12, 17, 6, 41200, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
