# Generated by Django 3.1.2 on 2021-02-16 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0017_auto_20210212_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 7, 28, 31, 871497, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
