# Generated by Django 3.1.2 on 2021-02-18 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0019_auto_20210216_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 12, 50, 15, 926155, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
