# Generated by Django 3.1.2 on 2021-02-18 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0020_auto_20210218_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 13, 35, 34, 724886, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
