# Generated by Django 3.1.2 on 2021-02-18 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0021_auto_20210218_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 13, 36, 52, 377016, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
