# Generated by Django 3.1.2 on 2021-02-19 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0022_auto_20210218_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 9, 50, 30, 860209, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
