# Generated by Django 3.1.2 on 2021-02-20 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0030_auto_20210220_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 12, 57, 38, 977112, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
