# Generated by Django 3.1.2 on 2021-03-18 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0037_auto_20210318_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 1, 38, 14, 926155, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
