# Generated by Django 3.1.2 on 2021-03-19 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0038_auto_20210318_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 12, 25, 5, 449557, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
