# Generated by Django 3.1.2 on 2021-03-19 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hms_auth', '0039_auto_20210319_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 12, 27, 26, 3033, tzinfo=utc), verbose_name='Expires'),
        ),
    ]
