# Generated by Django 3.1.2 on 2021-01-26 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('display_name', models.CharField(default='Permission Name', max_length=255, verbose_name='Permission Display Name')),
                ('name', models.CharField(max_length=255, verbose_name='Permission Name')),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('management', 'Management'), ('admin', 'Admin')], max_length=25, verbose_name='Category')),
            ],
            options={
                'db_table': 'hms_permission',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('gender', models.CharField(max_length=6, verbose_name='Gender')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('position', models.CharField(max_length=50, verbose_name='position')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/avatars/staff/', verbose_name='Avatar')),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Authenticator')),
            ],
            options={
                'db_table': 'hms_staff',
            },
        ),
        migrations.CreateModel(
            name='StaffPermissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('date_asigned', models.DateTimeField(auto_now=True, verbose_name='Date Asigned')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.permissionmodel', verbose_name='Permission Id')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id', to='staff.staffmodel', verbose_name='Staff Id')),
            ],
            options={
                'db_table': 'hms_staff_permission',
            },
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
