# Generated by Django 3.1.2 on 2021-02-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20210220_1307'),
        ('kitchen', '0005_foodordermodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='options.optionmodel', verbose_name='Food Group'),
        ),
    ]
